



name: Specific Push


on: 
  push: 
    branches: [develop]
    paths-ignore:
      -  '**.py'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: nameeeeeeee
        run: echo "heloooooooo world"
    