



name: Specific Push


on: 
  push: 
    branches: [develop]
    paths-ignore:
      -  '**.py'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: nameeeeeeee
        run: echo "heloooooooo world"



name: Workflow 2

on: 
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: name
        run: echo "second"
    